s_hdf5: src/usr/local/hdf5/lib/plugin/
s_build_ref: src/build_reference.py
s_convert: src/convert_pkl_to_txt.py
s_extract: src/extract_alignment.py
s_preprocess: src/preprocess_signal_fast5.py
s_mapping: src/run_signal_alignment_w_mapping.py
s_analyze: src/analyze_scores.py
s_utils: src/utils_cudadtw.py
s_porecupine: src/run_porecupine_tabix.py


f_kmer: kmer_models/kmer_model_r9.4.1.txt
p_kmer_size: 5
p_threshold_mm2: 0.0
p_threshold_dtw: 0.09
p_mapq_modified: 1
p_mapq_unmodified: 60
p_norm_zscore_ref: true
p_norm_zscore_query: true
p_cudtw_use: false
p_cudtw_last_k_signal: 256
p_cudtw_norm_signal_cutoff: -2.0
p_cudtw_top_k_contigs: 20
p_cudtw_top_k_mappings: 200
p_sort_merge_batch_size: 1000